import tkinter as tk

from tkinter.filedialog import asksaveasfile, askopenfilenames, askopenfilename

### Begin Functions ###
count = 0


def loadOnClick():
    count = count + 1
    print(count)
    #files = askopenfilenames(title='Choose your file(s)')
    #print(files)

def criterionOnClick():
    print("execute criterion")

def filterOnClick():
    print("filter")

#probably change this to write all the data generated by the previous functions to a singular file... could use this to get the file name
def saveOnClick():
    files = [('All Files', '*.*'),  
             ('Python Files', '*.py'), 
             ('Text Document', '*.txt')] 
    file = asksaveasfile(filetypes = files, defaultextension = files)
    print(file.name)
    
### End Functions ###

#initialize window
window = tk.Tk()
window.title("GUI 2.0")
window.geometry('725x325')

LABEL_WIDTH = 25
LABEL_HEIGHT = 15

BUTTON_HEIGHT= 5
BUTTON_WIDTH = 23

#add widgets

### Begin Load ###
loadLabel = tk.Label(window,
    text="Upload Files here! {}".format(count),
    width=LABEL_WIDTH,
    height=LABEL_HEIGHT,
    borderwidth=2,
    relief="sunken",
    )

loadLabel.grid(column=1,row=0)


loadButton = tk.Button(
    window,
    text="Load File(s)",
    width=BUTTON_WIDTH,
    height=BUTTON_HEIGHT,
    command= loadOnClick
    ) 
loadButton.grid(column=1,row=1)

### End load ###

### Begin Criterion ###

criterionLable= tk.Label(
    window,
    text="Doing the Quality Criterion \nCount",
    width=LABEL_WIDTH,
    height=LABEL_HEIGHT,
    borderwidth=2,
    relief="sunken",
    )

criterionLable.grid(column=2,row=0)

criterionButton = tk.Button(
    window,
    text="Criterion",
    width=BUTTON_WIDTH,
    height=BUTTON_HEIGHT,
    command=criterionOnClick
    )

criterionButton.grid(column=2,row=1)

### End Criterion ###

### Begin Wildline ###

wildlineLable= tk.Label(
    window,
    text="Filter Wildline",
    width=LABEL_WIDTH,
    height=LABEL_HEIGHT,
    borderwidth=2,
    relief="sunken",
    )

wildlineLable.grid(column=3,row=0)

wildlineButton = tk.Button(
    window,
    text="Filter",
    width=BUTTON_WIDTH,
    height=BUTTON_HEIGHT,
    command=filterOnClick
    )

wildlineButton.grid(column=3,row=1)

### End Wildline ###

### Begin Save ###

saveLable= tk.Label(
    window,
    text="",
    width=LABEL_WIDTH,
    height=LABEL_HEIGHT,
    )

saveLable.grid(column=4,row=0)

saveButton = tk.Button(
    window,
    text="Save File",
    width=BUTTON_WIDTH,
    height=BUTTON_HEIGHT,
    command=saveOnClick
    )

saveButton.grid(column=4,row=1)

### End Save ###

#build/display window with the attached widgets
window.mainloop()